services:
  - type: web
    name: painel-trading
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run painel_resultados_real.py --server.port=$PORT
    plan: free
  - type: worker
    name: bot-trading
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
