services:
  - type: web
    name: AutomaticTrade
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
